apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "virtual-test-harness.serviceAccountName" . }}
  labels:
    {{- include "virtual-test-harness.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
