#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# apply.sh – Apply the Terraform plan to Azure Government.
#
# Usage:
#   ./apply.sh [prefix] [environment]
#
#   prefix      – short label used in resource names (default: vth)
#   environment – deployment label (default: dev)
#
# The script applies the plan file generated by plan.sh if it exists,
# otherwise it runs an interactive apply.
#
# Prerequisites:
#   - Terraform initialised (run init.sh first).
#   - Azure CLI signed in to Azure Government.
# ---------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PREFIX="${1:-vth}"
ENVIRONMENT="${2:-dev}"

PLAN_FILE="${INFRA_DIR}/${PREFIX}-${ENVIRONMENT}.tfplan"

echo "==> Setting Azure CLI cloud to AzureUSGovernment …"
az cloud set --name AzureUSGovernment

export ARM_ENVIRONMENT="usgovernment"
export ARM_USE_CLI="true"

if [[ -f "${PLAN_FILE}" ]]; then
  echo "==> Applying saved plan: ${PLAN_FILE}"
  terraform -chdir="${INFRA_DIR}" apply "${PLAN_FILE}"
else
  echo "==> No saved plan found.  Running interactive apply …"
  terraform -chdir="${INFRA_DIR}" apply \
    -var="prefix=${PREFIX}" \
    -var="environment=${ENVIRONMENT}"
fi

echo "==> Apply complete."
