{{- if not .Values.useExternalVolumes }}
---
# ConfigMap: sensor config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtual-test-harness.fullname" . }}-config
  labels:
    {{- include "virtual-test-harness.labels" . | nindent 4 }}
data:
  config.json: |
    {{ .Values.config | toJson }}
---
# ConfigMap: inbox messages
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "virtual-test-harness.fullname" . }}-inbox
  labels:
    {{- include "virtual-test-harness.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.inbox }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
  {{- end }}
{{- end }}
